
spring:
  artemis:
    brokerUrl: ${BROKER_URL:(tcp://localhost:61616,tcp://localhost:61616)}
    user: ${ARTEMIS_USER:admin}
    password: ${ARTEMIS_PASSWORD:admin} 

destination.queue.name: demoQueue

