
spring:
  activemq:
    broker-url: ${BROKER_URL, failover(tcp://localhost:61616,tcp://localhost:61616)}
    user: ${ACTIVEMQ_USER, admin}
    password: ${ACTIVEMQ_PASSWORD, admin} 

destination.queue.name: demoQueue

