amqphub:
  amqp10jms:
    remote-url: ${BROKER_URL:failover:(amqp://localhost:5672,amqp://localhost:5672)}
    user: ${AMQ_USER:admin}
    password: ${AMQ_PASSWORD:admin}
    connectionCheckInterval: 1000
    pool:
      enabled: true
      maxConnections: 1

destination.queue.name: demoQueue
